# Generated by Django 5.2.7 on 2025-10-19 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=255)),
                ('number', models.CharField(blank=True, max_length=10, null=True)),
                ('postal_code', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=100)),
                ('country', models.CharField(default='Belgium', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('site_type', models.CharField(choices=[('HOSPITAL', 'Hôpital'), ('CLINIC', 'Clinique'), ('CABINET', 'Cabinet')], max_length=20)),
                ('address', models.ManyToManyField(related_name='site', to='location.address')),
            ],
        ),
    ]
