# Generated by Django 5.2.3 on 2025-09-07 20:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('CustomUser', '0003_remove_customuser_phone_doctor_patients'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_start', models.DateField()),
                ('hour_start', models.TimeField()),
                ('hour_end', models.TimeField()),
                ('report', models.TextField(blank=True, null=True)),
                ('medecin', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointment', to='CustomUser.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointment', to='CustomUser.patient')),
            ],
        ),
    ]
