# Generated by Django 5.2.3 on 2025-09-07 22:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0001_initial'),
        ('ordonnance', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointments',
            old_name='medecin',
            new_name='doctor',
        ),
        migrations.AddField(
            model_name='appointments',
            name='ordonnance',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ordonnance.ordonnance'),
        ),
    ]
