# Generated by Django 5.2.3 on 2025-09-08 21:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CustomUser', '0005_alter_doctor_patients'),
        ('appointment', '0002_rename_medecin_appointments_doctor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointments',
            name='doctor',
        ),
        migrations.RemoveField(
            model_name='appointments',
            name='ordonnance',
        ),
        migrations.AddField(
            model_name='appointments',
            name='medecin',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='appointment', to='CustomUser.doctor'),
            preserve_default=False,
        ),
    ]
