# Generated by Django 5.2.3 on 2025-09-09 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0003_remove_appointments_doctor_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointments',
            old_name='medecin',
            new_name='doctor',
        ),
    ]
