# Generated by Django 5.2.3 on 2025-09-08 14:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CustomUser', '0003_remove_customuser_phone_doctor_patients'),
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='address',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='customuser', to='location.address'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='doctor',
            name='sites',
            field=models.ManyToManyField(related_name='doctor', to='location.site'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='patients',
            field=models.ManyToManyField(blank=True, related_name='doctor', to='CustomUser.patient'),
        ),
    ]
