# Generated by Django 5.2.3 on 2025-09-08 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CustomUser', '0004_customuser_address_doctor_sites_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='patients',
            field=models.ManyToManyField(blank=True, related_name='doctors', to='CustomUser.patient'),
        ),
    ]
