# Generated by Django 5.2.3 on 2025-09-08 21:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CustomUser', '0005_alter_doctor_patients'),
        ('location', '0002_alter_site_site_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='location.address'),
        ),
    ]
