# Generated by Django 5.2.3 on 2025-09-24 09:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CustomUser', '0007_remove_doctor_id_remove_patient_id_alter_doctor_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='patients',
            field=models.ManyToManyField(blank=True, related_name='doctors', to=settings.AUTH_USER_MODEL),
        ),
    ]
