# Generated by Django 5.2.3 on 2025-09-07 20:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medicament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_m', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Ordonnance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_o', models.DateField()),
                ('contentReport_o', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='OrdonnanceMedicament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('medicament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ordonnance.medicament')),
                ('ordonnance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ordonnance.ordonnance')),
            ],
        ),
        migrations.AddField(
            model_name='ordonnance',
            name='medicaments',
            field=models.ManyToManyField(through='ordonnance.OrdonnanceMedicament', to='ordonnance.medicament'),
        ),
    ]
