# Generated by Django 5.2.3 on 2025-09-07 22:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CustomUser', '0003_remove_customuser_phone_doctor_patients'),
        ('ordonnance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordonnance',
            name='doctor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='CustomUser.doctor'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ordonnance',
            name='patient',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='CustomUser.patient'),
            preserve_default=False,
        ),
    ]
