# Generated by Django 5.2.3 on 2025-09-08 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ordonnance', '0002_ordonnance_doctor_ordonnance_patient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordonnance',
            name='doctor',
        ),
        migrations.RemoveField(
            model_name='ordonnance',
            name='patient',
        ),
    ]
