# Generated by Django 5.2.5 on 2025-09-27 15:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CustomUser', '0008_alter_doctor_patients'),
        ('ordonnance', '0003_remove_ordonnance_doctor_remove_ordonnance_patient'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordonnance',
            name='doctor',
            field=models.ForeignKey(default=5000, on_delete=django.db.models.deletion.PROTECT, related_name='ordonnances', to='CustomUser.doctor'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ordonnance',
            name='patient',
            field=models.ForeignKey(default=5000, on_delete=django.db.models.deletion.CASCADE, related_name='ordonnances', to='CustomUser.patient'),
            preserve_default=False,
        ),
    ]
